### ISSUE TITLE
LOCAL-environment token validation

### ISSUE THREAD

**Issue by mrac** [zalando-incubator/solution-center-login#3]
When validating tokens in 'LOCAL' environment, it seems it does a real validation - it performs a request to a token service on external environment:

`environmentsService.getTokensAPI(self.getEnvironment())`

`GET https://tm-dev-ext.norris.zalan.do/tokens 401 (Unauthorized)`

I see 2 drawbacks here:
1) we cannot mock the login process
2) we depend on the stability of that external service, when running our LOCAL app

Which environment is it?
May be the token-service domain should not be hardcoded for LOCAL environment?

And the second question:
- what is the fifth possible environment ''DEVELOPMENT' mentioned in the README?

**Comment by dami-gg** [comment]
As discussed we're adding an option to set the token service when configuring the environment for local environments.

Regarding the second question we're getting rid of it after unifying all the environments across Brand Solutions, it's a leftover due to us calling STAGING environment as DEVELOPMENT previously ;)

**Comment by dami-gg** [comment]
This has been implemented in the new version 0.1.5

Regarding the DEVELOPMENT environment question, a heads-up: we've decided to keep it for our development process in the Central Services team as a kind of stage since otherwise every time we want to test something, if we do it directly in the stage environment you'll be relying on for your own stage environments and we crash it, it might be a bit cumbersome for you.

So summing it up we'll use it to try to keep the stage environment more stable for you all, service providers teams.
