### ISSUE TITLE
mechant-id

### ISSUE THREAD

**Issue by mrac** [zalando-incubator/solution-center-login#5]
There is no data about currently selected brand. Should we use a separate endpoint to read it, or will it be added to localStorage?

**Comment by dami-gg** [comment]
It will be added to a cookie, it's already implemented but not released

**Comment by dami-gg** [comment]
We've added it to a cookie named SC_BRAND. We store the id of the brand but you must check anyway in your app without assuming it's going to be there, because it might happen that if the user doesn't choose a brand through the Solution Center this is empty. 

We've provided getter and setter methods that are handy for that.

@cjhowald we must add something about this in the README file
