### ISSUE TITLE
Read and write to new cookie

### ISSUE THREAD

**Issue by cjhowald** [zalando-incubator/solution-center-login#72]
Currently, tokens are read and written from cookies with the key `SC_TOKEN`. We should introduce a new cookie key for tokens from the new service, so they don't clash with existing tokens and so users can be authenticated against old and new services at the same time.

**Comment by cjhowald** [comment]
Proposed name: `SC_TOKEN_NEW`.

**Comment by gregdeane** [comment]
The only problem with `SC_TOKEN_NEW` is that `NEW` will eventually lose its meaning. We should pick a name that will be appropriate for the future as well (since users will have this cookie installed and we won't be able to change the name).

Maybe `SC2_TOKEN` (which isn't very good) or something that will work in the future (since "new" will eventually be "old").

**Comment by cjhowald** [comment]
Good point. I would prefer to leave the SC prefix alone, since everything has that same prefix, and it's not really a new solution center. Could go `SC_TOKEN_2`. Feels a bit lame, but gives us a path for future cookie keys if we have to change it again. `NEW` might lose it's meaning, but 2 is pretty clear, right?

**Comment by gregdeane** [comment]
Yeah, I'd say `2` is better than `NEW`. If no other objections, let's go `2`.

**Comment by dami-gg** [comment]
I was hesitating when naming the cookie in the navigation if we should be less explicit in the cookie names, since SC_BUSINESS_PARTNER was describing it too much and perhaps is not good to show that much information. I still wonder whether SC_BP would be better and perhaps we could apply the same logic here and name this SC_T or something similar that only we know what it's about. What do you guys think?

**Comment by dami-gg** [comment]
Besides that, I'd also be against using NEW. Even in the communicator we shouldn't be using TOKEN_SERVICE_NEW but TOKEN_SERVICE and renaming the old one to TOKEN_SERVICE_OLD to be deleted afterwards

**Comment by gregdeane** [comment]
I'm on board with being less specific in the cookie name since internally we will know what it means. I'm not sure if there's a security reason to use a more obscure name but I think it's one better above using NEW or 2.

**Comment by gregdeane** [comment]
Definitely in sc-communicator, it's a stupid name. It was a quick win that, as always, makes it harder in the end.

**Comment by cjhowald** [comment]
I don't see much benefit from changing the cookie name, only a small amount of obscurity added.

I do agree we should make the changes to the communicator in a new major version. That will slightly affect our updates to this module.
