### ISSUE TITLE
Coupling to navigation component

### ISSUE THREAD

**Issue by mrac** [zalando-incubator/solution-center-login#94]
In version 4 there's a breaking change log entry:

> solution-center-navigation is required for authentication, since it will obtain an access token given the session token and business partner

Why fairly unrelated UI component (navigation) is necessary part in the logic confirming user's identity?

**Comment by cjhowald** [comment]
I removed that entry from the changelog, since it was misleading. Login does not depend on navigation. A user is authenticated and acquires a session token from the new services upon login.

Navigation is responsible for acquiring access tokens based on the current business partner, however. For more detail, see [our documentation](https://docs.google.com/document/d/1ToIIoA08EMmQOGuHfUUjfy_wp5b4tylF4K-sORfLqD4/edit#heading=h.bwtdoqqt6ndl).

**Comment by cjhowald** [comment]
Closing this issue, since it is resolved.
