### ISSUE TITLE
UseOldToken needed to be passed

### ISSUE THREAD

**Issue by mrac** [zalando-incubator/solution-center-login#96]
Even though I configure to use old token by:
```ScAuthenticationServiceProvider.useOldToken(true);```

I have to pass the flag in the methods anyway for most of public methods, like ```login, silentLogin, getToken, setToken``` etc.

**Comment by cjhowald** [comment]
The new login uses new tokens by default in all cases. The `useOldToken` configuration is intended for exceptional cases where you have upgraded but need to use the old token temporarily. Additionally, some methods accept a parameter to override the default.

We can modify the behavior so all public methods give preference to the `useOldToken` configuration when set rather than defaulting to the new token.

Note however that this configuration is temporal and only needed during migration as a fallback. It will be removed along with all old/new branching and parameters when the old services are retired.

**Comment by mrac** [comment]
It just feels weird and inconsistent for the API, to configure library to work in a certain way and still have to parametrise each of public method to work in the same way.

Do you agree?
Can we improve that?

I think all code is more or less temporary. I would not use this argument to smuggle bad code in.

**Comment by mrac** [comment]
Sorry, I missed that #103 would fix that. Thanks!

**Comment by cjhowald** [comment]
Yes, as of #103 all public methods respect `useOldToken`, so you should never need to pass the extra parameter.

The only reason for the parameterization is to support hybrid login, where the configuration may differ from the current path. For example, the login page makes calls to `login` `redirectToHomeIfAuthenticated` and `getToken` based on whether the requesting application is in the new or old context, so must force a particular token regardless of its own configuration.

Once the migration is completed, hybrid login will be removed along with these parameters (see #75).
