### ISSUE TITLE
login method fails in new-token backend is not ready

### ISSUE THREAD

**Issue by mrac** [zalando-incubator/solution-center-login#98]
In ```login()``` method the promise is always rejected, because it tries to communicate with both old and new token endpoint in the same time, regardless passed ```expectOldToken``` flag.

So it's not backward compatible, until the new token backend service and its mock is up and running. Is it by purpose or it's a bug?

**Comment by cjhowald** [comment]
In order to support hybrid login, `login` attempts to acquire a token from both old and new services. The `expectOldToken` parameter determines success (i.e. if we are expecting an old token and an old token is not acquired, it is a failure, even if a new token is acquired).

The promise will not be rejected if the credentials you enter are valid for the token you are expecting (old or new). This has been tested in integration. Could you provide more details about the failure you are seeing?

**Comment by cjhowald** [comment]
In case it is related to your issue, note that in the environment configuration there is now just one service for users and token, `USER_SERVICE`, and `TOKEN_SERVICE` is obsolete. You may need to change your local environment configuration. See the [communicator changelog](https://github.com/zalando-incubator/solution-center-communicator/blob/master/CHANGELOG.md#300-2017-02-08) for more details.

**Comment by cjhowald** [comment]
Closing since login is accessing old and new endpoints as expected. The services are deployed in all environments.
